// Generated by @-create-pw-date-test on 2026-04-01
//
// TC-1-A-BRT — Config A, Calendar Popup, BRT
// Config: enableTime=false, ignoreTimezone=false, useLegacy=false (DataField7)
// Timezone: America/Sao_Paulo (UTC-3)
// Scenario: Select Mar 15 via calendar popup.
// Expected: raw="2026-03-15", api="2026-03-15"
// Bugs: None in BRT (Bug #7 only affects UTC+)

const { test, expect } = require('@playwright/test');
const { FORM_TEMPLATE_URL, FIELD_MAP } = require('./vv-config');
const {
    gotoAndWaitForVVForm,
    getCodePath,
    verifyField,
    captureFieldValues,
    getBrowserTimezone,
    selectDateViaPopup,
} = require('./vv-helpers');

const CONFIG = 'A';
const FIELD_NAME = FIELD_MAP[CONFIG].field;
const EXPECTED_RAW = '2026-03-15';
const EXPECTED_API = '2026-03-15';
const EXPECTED_TZ_OFFSET = 'GMT-0300';

test.describe('TC-1-A-BRT: Calendar Popup, Config A, BRT', () => {
    test('select Mar 15 via popup, verify storage and API values', async ({ page }) => {
        // Navigate to fresh form and wait for VV.Form ready
        await gotoAndWaitForVVForm(page, FORM_TEMPLATE_URL);

        // P3: Verify BRT timezone
        const dateStr = await getBrowserTimezone(page);
        expect(dateStr).toContain(EXPECTED_TZ_OFFSET);

        // P5: Verify V1 code path
        const isV2 = await getCodePath(page);
        expect(isV2).toBe(false);

        // P6: Verify field exists with expected config
        const fieldName = await verifyField(page, {
            enableTime: false,
            ignoreTimezone: false,
            useLegacy: false,
            enableInitialValue: false,
        });
        expect(fieldName).toBe(FIELD_NAME);

        // Select March 15, 2026 via calendar popup
        await selectDateViaPopup(page, FIELD_NAME, 2026, 3, 15);

        // Capture and verify stored values
        const values = await captureFieldValues(page, FIELD_NAME);
        expect(values.raw).toBe(EXPECTED_RAW);
        expect(values.api).toBe(EXPECTED_API);

        // Verify BRT active via isoRef (BRT midnight = UTC 03:00)
        const isoRef = await page.evaluate(() => new Date(2026, 2, 15, 0, 0, 0).toISOString());
        expect(isoRef).toBe('2026-03-15T03:00:00.000Z');
    });
});
